services:
  oxidized:
    build: .
    container_name: oxidized
    restart: always
    ports:
      - "80:8888"
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    volumes:
      - ./oxidized:/root/.config/oxidized/
      - ./oxidized/output:/root/.config/output
